DROP TABLE employees;

CREATE TABLE employees (
    employee_id    NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 90001 INCREMENT BY 1,
    employee_name  VARCHAR2(50) NOT NULL,
    job_title      VARCHAR2(50) NOT NULL,
    manager_id     NUMBER(10),
    date_hired     DATE NOT NULL,
    salary         NUMBER(10) NOT NULL,
    department_id  NUMBER(5) NOT NULL
);

ALTER TABLE employees
ADD CONSTRAINT employee_id_pk PRIMARY KEY (employee_ID);

ALTER TABLE employees
ADD CONSTRAINT manager_id_pk FOREIGN KEY (manager_id)
REFERENCES employees(employee_id)
ON DELETE CASCADE
INITIALLY DEFERRED DEFERRABLE;  -- Self referencing FK on employees, record might not exist yet.

ALTER TABLE employees
ADD CONSTRAINT department_id_fk FOREIGN KEY (department_id)
REFERENCES departments(department_id)
ON DELETE CASCADE;