CREATE TABLE departments (
    department_id    NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
    department_name  VARCHAR2(50) NOT NULL,
    location         VARCHAR2(50) NOT NULL
);

ALTER TABLE departments
ADD CONSTRAINT department_id_pk PRIMARY KEY (department_id);
